theme: jekyll-theme-minimal
title: 'Single Cell RNA-Seq Analysis'
show_downloads: True
google_analytics: True
navigation:
  - title: Home
    url: /

  - heading: Introduction and Lectures
  - title: Intro to the Workshop and Core
    url: base/welcome

  - heading: Support
  - title: Schedule
    url: base/schedule
  - title: Slack
    url: base/slack
  - title: Cheat Sheets
    url: base/cheatSheetIndex
  - title: Software and Links
    url: software_scripts/software
  - title: Scripts
    url: software_scripts/scripts_links
  - title: GitHub repository
    url: https://github.com/ucdavis-bioinformatics-training/2023-December-Single-Cell-RNA-Seq-Analysis
  - title: Biocore website
    url: http://bioinformatics.ucdavis.edu

  - heading: Prerequisites
  - title: CLI
    url: base/cli_prerequisites
  - title: R
    url: base/r_prerequisites_fixed

  - heading: Data Reduction
  - title: Files and Filetypes
    url: data_reduction/filetypes
  - title: Project setup
    url: data_reduction/project_setup
  - title: Generating Expression Matrix
    url: data_reduction/Expression_Matrix

  - heading: scRNAseq Analysis
  - title: Prepare scRNAseq Analysis
    url: data_analysis/00-prepare_fixed
  - title: Part 1: Create Object
    url: data_analysis/01-create_object_fixed
  # - title: Part 2: Filtering
  #   url: data_analysis/02-filtering
  # - title: Part 3: Normalization and scaling
  #   url: data_analysis/03-normalize_scale
  # - title: Part 4: Dimensionality reduction
  #   url: data_analysis/04-dimensionality_reduction
  # - title: Part 5: Doublet detection
  #   url: data_analysis/05-doublet_detection
  # - title: Part 6: Integration
  #   url: data_analysis/06-integration
  # - title: Part 7: Clustering and cell type
  #   url: data_analysis/07-clustering_celltype
  # - title: Part 8: Enrichment and DE
  #   url: data_analysis/08-de_enrichment
